spring:
  redis:
    host: 127.0.0.1
    password: ''
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: jeecg-demo
          uri: lb://jeecg-demo
          predicates:
            - Path=/test/**,/api/**,/bigscreen/template1/**,/bigscreen/template2/**
        - id: jeecg-system
          uri: lb://jeecg-system
          predicates:
            - Path=/sys/**,/oss/file/**,/webSocketApi/**,/online/**,/message/**
        - id: jeecg-system-websocket
          uri: lb:ws://jeecg-system
          predicates:
            - Path=/websocket/**
        - id: jeecg-demo-websocket
          uri: lb:ws://jeecg-demo
          predicates:
            - Path=/vxeSocket/**
management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace